import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { TextLeft } from './index.style'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Demo <a href="https://nextjs.org">Next.js</a>
        </h1>

        <div className={styles.description}>
          <code className={styles.code}>project structure</code>
          <ul>
            <TextLeft>
              package.json {'=>'} it includes all dependencies and scripts required for the project
            </TextLeft>
            <TextLeft>
              next.config.json {'=>'} it includes all settings desired for the project
            </TextLeft>
            <TextLeft>
              .next folder {'=>'} it is created when running the project and serves the app
            </TextLeft>
            <TextLeft>
              node modules folder {'=>'} all the required dependencies
            </TextLeft>
            <TextLeft>
              public folder {'=>'} holds all the public resources for the application svg, ico, etc
            </TextLeft>
            <TextLeft>
              pages folder {'=>'} it has the entire routing feature of the app
            </TextLeft>
          </ul>
        </div>
      </main>
    </div>
  )
}
